#################LISTAS####################
colores = ['Rojo', 'Azul', 'Amarillo', 'Naranja', 'Violeta', 'Verde']
#input()
print(colores)
print(type(colores))
print(colores[2])
print("Tamaño de colores: ", len(colores))
print(colores[0:2])
print(colores[:2])
colores.append('Blanco')      
print(colores)
colores.insert(3, 'Negro')
print(colores)
colores.extend(['Marron', 'Gris'])   
print(colores)
print(colores.index('Azul'))
#colores.remove('Magenta')
colores.remove('Marron')
print(colores)
colores.insert(8, 'Marron')
print(colores)
print(colores.pop())
tamanio = len(colores)
print("tamanio = ", tamanio)
#print(colores.pop(tamanio))
lista_triplicada = colores * 3
print("lista_triplicada: ", lista_triplicada)
print("Ordenando:")
print()
colores_ordenados = colores.sort()
print(colores_ordenados)
numeros = [10, 9, 8, 7, 6 , 5 , 4, 3, 2, 1]
print("Ordenando numeros: ")
numeros.sort()
print(numeros)
numeros.sort(reverse = True)
print("De menor a mayor: ", numeros)

print("############TUPLAS#########")
tupla_colores = tuple(colores)
print()
print()
print("tupla_colores: ", tupla_colores)
print(tupla_colores[0])
print(tupla_colores[2])
print('Rojo' in tupla_colores)
print(tupla_colores.count('Rojo'))
tupla_simple = ('Blanco')
print(tupla_simple)
datos_persona = 'Gaspar', 5, 8, 1999
print(datos_persona)
nombre, dia, mes, año = datos_persona
print(nombre)
print(dia)
print(mes)
print(año)
print("Nombre: ", nombre, " - Dia:", dia, " - Mes: ", mes, "- Año: ", año)
lista_persona = list(datos_persona)
print(lista_persona)
